steps:
  - name: 'gcr.io/cloud-builders/docker'
    args: ['build', '-t', 'gcr.io/b-profiles-461910/3bprofiles', '.']

  - name: 'gcr.io/cloud-builders/docker'
    args: ['push', 'gcr.io/b-profiles-461910/3bprofiles']

  - name: 'gcr.io/cloud-builders/gcloud'
    args:
      [
        'run', 'deploy', '3bprofiles',
        '--image', 'gcr.io/b-profiles-461910/3bprofiles',
        '--region', 'asia-south1',
        '--platform', 'managed',
        '--allow-unauthenticated'
      ]

options:
  defaultLogsBucketBehavior: REGIONAL_USER_OWNED_BUCKET
