const SubAdmin = require('../models/SubAdmin');
const gcs = require('../utils/gcloud'); // Your GCS utility

// @desc    Register a new sub-admin
// @route   POST /api/subadmins/register
exports.registerSubAdmin = async (req, res) => {
  try {
    const { name, email, phone, dob, address } = req.body;

    // ✅ Check required file
    if (!req.files || !req.files.verificationDocument) {
      return res.status(400).json({ message: 'Verification document is required.' });
    }

    const existingSubAdmin = await SubAdmin.findOne({
      $or: [{ email }, { phone }]
    });

    if (existingSubAdmin) {
      return res.status(400).json({
        message: 'Sub-admin with this Email or Phone already exists.'
      });
    }

    // ✅ Generate Password
    const yearOfBirth = new Date(dob).getFullYear();
    if (!yearOfBirth || isNaN(yearOfBirth)) {
      return res.status(400).json({ message: 'Invalid Date of Birth format.' });
    }

    const nameInitials = name.substring(0, 4).toLowerCase();
    const autoGeneratedPassword = `3B${nameInitials}@${yearOfBirth}`;

    // =========================
    // ✅ Upload Verification Doc
    // =========================
    const verificationFile = req.files.verificationDocument[0];

    const verificationUpload = await gcs.uploadBufferToGCS(
      verificationFile.buffer,
      verificationFile.originalname,
      'verification-documents',
      verificationFile.mimetype
    );

    // =========================
    // ✅ Upload Profile Picture (optional)
    // =========================
    let profileUpload = { url: '', id: '' };

    if (req.files.profilePicture) {
      const profileFile = req.files.profilePicture[0];

      profileUpload = await gcs.uploadBufferToGCS(
        profileFile.buffer,
        profileFile.originalname,
        'profile-pictures',
        profileFile.mimetype
      );
    }

    // =========================
    // ✅ Save to DB
    // =========================
    const subAdmin = await SubAdmin.create({
      name,
      email,
      phone,
      dob,
      address,
      password: autoGeneratedPassword,
      verificationDocument: {
        url: verificationUpload.url,
        id: verificationUpload.id
      },
      profilePicture: profileUpload
    });

    res.status(201).json({
      message: "Sub-admin created successfully",
      autoGeneratedPassword,
      subAdminData: subAdmin
    });

  } catch (error) {
    console.log("❌ ERROR:", error);

    return res.status(500).json({
      message: "Server error",
      error: error.message
    });
  }
};

exports.setPermissions = async (req, res) => {
  try {
    const { subAdminId, permissions } = req.body;

    const subAdmin = await SubAdmin.findById(subAdminId);

    if (!subAdmin) {
      return res.status(404).json({ message: "SubAdmin not found" });
    }

    subAdmin.permissions = permissions;

    await subAdmin.save();

    res.json({
      message: "Permissions updated successfully",
      permissions: subAdmin.permissions
    });

  } catch (err) {
    res.status(500).json({ message: err.message });
  }
};

// @desc    Authenticate a sub-admin & get their profile
// @route   POST /api/subadmins/login
const axios = require("axios");

const API_KEY = "ed737417-3faa-11f0-a562-0200cd936042";

exports.sendLoginOtpSubAdmin = async (req, res) => {
  try {
    const { phone } = req.body;

    const subAdmin = await SubAdmin.findOne({ phone });

    if (!subAdmin) {
      return res.status(404).json({
        message: "Sub-admin not found"
      });
    }

    // 🔥 Send OTP via 2Factor
    const response = await axios.get(
      `https://2factor.in/API/V1/${API_KEY}/SMS/${phone}/AUTOGEN`
    );

    // 🔥 Save sessionId instead of OTP
    subAdmin.otp = {
      code: response.data.Details, // sessionId
      expiresAt: new Date(Date.now() + 5 * 60 * 1000)
    };

    await subAdmin.save();

    res.status(200).json({
      message: "OTP sent successfully"
    });

  } catch (error) {
    console.log("OTP SEND ERROR:", error.response?.data || error.message);

    res.status(500).json({
      message: "Failed to send OTP",
      error: error.message
    });
  }
};

exports.verifyLoginOtpSubAdmin = async (req, res) => {
  try {
    const { phone, otp } = req.body;

    const subAdmin = await SubAdmin.findOne({ phone });

    if (!subAdmin || !subAdmin.otp) {
      return res.status(400).json({
        message: "Invalid request"
      });
    }

    const sessionId = subAdmin.otp.code;

    // 🔥 Verify OTP via 2Factor
    const response = await axios.get(
      `https://2factor.in/API/V1/${API_KEY}/SMS/VERIFY/${sessionId}/${otp}`
    );

    if (response.data.Status !== "Success") {
      return res.status(401).json({
        message: "Invalid or expired OTP"
      });
    }

    // ✅ Clear OTP after success
    subAdmin.otp = undefined;
    await subAdmin.save();

    const userData = subAdmin.toObject();
    delete userData.password;

    res.status(200).json({
      message: "Login successful",
      role: "sub-admin", // ✅ REQUIRED
      user: userData
    });

  } catch (error) {
    console.log("OTP VERIFY ERROR:", error.response?.data || error.message);

    res.status(500).json({
      message: "OTP verification failed",
      error: error.message
    });
  }
};

// @desc    Get all sub-admins
// @route   GET /api/subadmins/
// @desc    Get all sub-admins
// @route   GET /api/subadmins/
exports.getAllSubAdmins = async (req, res) => {
  try {
    const subAdmins = await SubAdmin.find({})
      .select("-password") // 🔥 never send password
      .sort({ createdAt: -1 });

    res.status(200).json(subAdmins);

  } catch (error) {
    res.status(500).json({
      message: 'Server Error',
      error: error.message
    });
  }
};

// @desc    Get a single sub-admin by their database _id
// @route   GET /api/subadmins/:id
// @desc    Get a single sub-admin by their database _id
// @route   GET /api/subadmins/:id
exports.getSubAdminById = async (req, res) => {
  try {
    const subAdmin = await SubAdmin.findById(req.params.id)
      .select("-password");

    if (!subAdmin) {
      return res.status(404).json({
        message: 'Sub-admin not found'
      });
    }

    res.status(200).json(subAdmin);

  } catch (error) {
    res.status(500).json({
      message: 'Server Error',
      error: error.message
    });
  }
};

// @desc    Update sub-admin profile details
// @route   PUT /api/subadmins/:id
exports.updateSubAdmin = async (req, res) => {
  try {
    const subAdmin = await SubAdmin.findById(req.params.id);
    if (!subAdmin) {
      return res.status(404).json({ message: 'Sub-admin not found.' });
    }

    if (req.file) {
      if (subAdmin.profilePicture && subAdmin.profilePicture.id) {
        await gcs.deleteFileFromGCS(subAdmin.profilePicture.id);
      }
      const uploadResult = await gcs.uploadBufferToGCS(
        req.file.buffer, req.file.originalname, 'profile-pictures', req.file.mimetype
      );
      subAdmin.profilePicture = { url: uploadResult.url, id: uploadResult.id };
    }

    subAdmin.name = req.body.name || subAdmin.name;
    subAdmin.phone = req.body.phone || subAdmin.phone;
    subAdmin.dob = req.body.dob || subAdmin.dob;
    subAdmin.address = req.body.address || subAdmin.address;
    
    // Logic to update password if provided
    if (req.body.password) {
        subAdmin.password = req.body.password;
    }

    const updatedSubAdmin = await subAdmin.save();
    res.status(200).json(updatedSubAdmin);
  } catch (error) {
    res.status(500).json({ message: 'Server Error', error: error.message });
  }
};

// @desc    Update a sub-admin's status
// @route   PATCH /api/subadmins/:id/status
exports.updateSubAdminStatus = async (req, res) => {
  try {
    const { status } = req.body;
    if (!['active', 'inactive'].includes(status)) {
      return res.status(400).json({ message: "Status must be 'active' or 'inactive'." });
    }

    const subAdmin = await SubAdmin.findByIdAndUpdate(req.params.id, { status }, { new: true });
    if (!subAdmin) { return res.status(404).json({ message: 'Sub-admin not found.' }); }
    res.status(200).json(subAdmin);
  } catch (error) {
    res.status(500).json({ message: 'Server Error', error: error.message });
  }
};

// @desc    Delete a sub-admin
// @route   DELETE /api/subadmins/:id
exports.deleteSubAdmin = async (req, res) => {
  try {
    const subAdmin = await SubAdmin.findById(req.params.id);
    if (!subAdmin) { return res.status(404).json({ message: 'Sub-admin not found.' }); }

    const deletionPromises = [];
    if (subAdmin.verificationDocument && subAdmin.verificationDocument.id) {
      deletionPromises.push(gcs.deleteFileFromGCS(subAdmin.verificationDocument.id));
    }
    if (subAdmin.profilePicture && subAdmin.profilePicture.id) {
      deletionPromises.push(gcs.deleteFileFromGCS(subAdmin.profilePicture.id));
    }

    await Promise.all(deletionPromises);
    await subAdmin.deleteOne();

    res.status(200).json({ message: 'Sub-admin and associated files deleted successfully.' });
  } catch (error) {
    res.status(500).json({ message: 'Server Error', error: error.message });
  }
};